### ISSUE TITLE
New Tool - Projection configuration

### ISSUE THREAD

**Issue by qulle** [qulle/oltb#15]
Tool to add, configure and change the desired projection during runtime.

**Comment by sl0burn** [comment]
there is an example of this for ol at https://openlayers.org/en/latest/examples/reprojection-by-code.html

**Comment by qulle** [comment]
@sl0burn Yes i am planning to do a mix of the link you provided and this one https://openlayers.org/en/latest/examples/reprojection.html

**Comment by qulle** [comment]
More complicated function then i initially anticipated. Some tricky corner cases that needs some more in dept investigation. Will pause and work on the rest of the tasks for the upcoming beta3.

Reminders to next time:
- Handle Feature and Vector layers 
- Multiple layers
- TypeError: coordinates must be finite numbers
- EPSG:7789

**Comment by HPNIRASSWE** [comment]
@qulle  Could you contact me over email? A professional request? hans.palmborg@niras.se

**Comment by qulle** [comment]
@HPNIRASSWE 9fa092dbaad481cd38b63e0e587eb703
