### ISSUE TITLE
Error when trying to delete Map Layers

### ISSUE THREAD

**Issue by Vazquez1240** [qulle/oltb#33]
Hello, I encountered an error when trying to delete the map layers. The error is due to a type of map layer that lacks the 'getFeature' function.

**Comment by Vazquez1240** [comment]
I was able to fix the error by implementing a conditional to check if it's an instance of VectorLayer. If it is, proceed with the normal flow; otherwise, just delete it as it lacks the 'getFeatures' function.

**Comment by qulle** [comment]
Hi,
Thanks for your bug report.
Couldn't find any PR, but I fixed the bug in today's release (v2.2.0). 
I added a note in the release documentation that it was reported by you.

Br. Daniel
